s = """CTCACGTATATACAAATGGTAGCGGACGAACCACTCCGGGAGCTGCTCCTGCAGACAAGC
ACCCGTTGGGCAACAGACCCATATCTATCAGGACCCTCTCTTCGTTGCATAGTAGGTGAG
CCGTGCCGTATGATAACGTCCAATCCACTATGCCTCGTTGATGTCATGTTGTGACGATGT
GGACGACGCCACTTCTCCCATGTAAATCAGCCGTGGCTTAAAAATAGCACTGTCTGGCCG
TAAGCATCTCCGCGGCGTGATACCCTGGGACACGACCAGCCGTCTCAAGTACATCGCGGT
GTGCTCCGTCGGGGCAATTTAGCATATTTTCATGGCAGCGTTCTGGGTTAATAGTCCATG
GGTGTGTCCAGCAGACCCGCAATGGACTCATAGTTGATTCCCGAGGTATCTGGCTTTTTT
CCAATATTTTGTTATACGCGCTGAGAGGCCTTCCGCTGCCGTCAGTGGTGGAGTATAGGT
CTCGTACGTGCCATTTAACACCCTTACAGAACAGTCTCCGGCCTAGGATAAACTAAGAGC
ACAACACGGGAATGAGGTTTCTCGACTATGCTCGGATGGAGGTGGCCTCGAGGCCATGGA
GCGTCCACCGACCCACAGGCCTTCCTCATGGTGGTTTGAACAGACTGAGATAATGTCTAA
CTAGCCAAGAAGCATGCTTCAGCGGTGACGCAGTAACTACCCAAAAATAGACTTCGCGGG
GGATGGTTGAATCCAACGCAAAGTTTAGGTCTACATACGCCTCCTTTGCCTGATCTTGTC
CGATTATCGAGAAACGCTTGTCAAGGAAGAGGACAGTTGCGAAATCGCATCAATTGCATG
CGGGCCCGGCGATACTAGGGTCACGGGGTAATTACAGCATATAG"""
t = 'TAAACGCTCTGCACTGCTGGGCCGCTGCGAGCATCCGCAGGAGGCCTGC'
# seq = []
# for i,v in enumerate(dna):
#     for i2,v2 in enumerate(motif):
#         if v == v2:
#             seq.append(i+1)
#print(seq)
pos = 0
positions = []
for i in range(len(t)):
    for j in range(pos, len(s)):
        pos += 1
        if len(positions) < len(t):
            if t[i] == s[j]:
                positions.append(pos)
                break
print(*positions, sep=' ')
